musica(1, "Psychosocial", ["Guitarra", "Bateria", "Baixo", "Teclado"], ["Corey Taylor", "Jim Root", "Shawn Crahan", "Sid Wilson", "Craig Jones", "Alessandro Venturella", "Jay Weinberg"], "Heavy Metal", "05/01/2008", "I did my time and I want out...", "Slipknot", 9).
musica(2, "Duality", ["Guitarra", "Bateria", "Baixo", "Teclado"], ["Corey Taylor", "Jim Root", "Shawn Crahan", "Sid Wilson", "Craig Jones", "Alessandro Venturella", "Jay Weinberg"], "Heavy Metal", "24/05/2004", "I push my fingers into my eyes...", "Slipknot", 8).
musica(3, "Before I Forget", ["Guitarra", "Bateria", "Baixo", "Teclado"], ["Corey Taylor", "Jim Root", "Shawn Crahan", "Sid Wilson", "Craig Jones", "Alessandro Venturella", "Jay Weinberg"], "Heavy Metal", "09/07/2004", "Stapled shut, inside an outside world and I'm", "Slipknot", 7).
musica(4, "Wait and Bleed", ["Guitarra", "Bateria", "Baixo", "Teclado"], ["Corey Taylor", "Jim Root", "Shawn Crahan", "Sid Wilson", "Craig Jones", "Alessandro Venturella", "Jay Weinberg"], "Heavy Metal", "28/06/1999", "I've felt the hate rise up in me...", "Slipknot", 8).
musica(5, "The Devil in I", ["Guitarra", "Bateria", "Baixo", "Teclado"], ["Corey Taylor", "Jim Root", "Shawn Crahan", "Sid Wilson", "Craig Jones", "Alessandro Venturella", "Jay Weinberg"], "Heavy Metal", "24/08/2014", "Undo these chains, my friend...", "Slipknot", 9).
musica(6, "Snuff", ["Guitarra", "Bateria", "Baixo", "Piano"], ["Corey Taylor", "Jim Root", "Shawn Crahan", "Sid Wilson", "Craig Jones", "Alessandro Venturella", "Jay Weinberg"], "Heavy Metal", "09/09/2008", "Bury all your secrets in my skin...", "Slipknot", 8).
musica(7, "Vermilion", ["Guitarra", "Bateria", "Baixo", "Piano"], ["Corey Taylor", "Jim Root", "Shawn Crahan", "Sid Wilson", "Craig Jones", "Alessandro Venturella", "Jay Weinberg"], "Heavy Metal", "12/07/2004", "She isn't real, I can't make her real...", "Slipknot", 7).
musica(8, "The Nameless", ["Guitarra", "Bateria", "Baixo", "Teclado"], ["Corey Taylor", "Jim Root", "Shawn Crahan", "Sid Wilson", "Craig Jones", "Alessandro Venturella", "Jay Weinberg"], "Heavy Metal", "06/09/2004", "You don't know what you've got until it's gone...", "Slipknot", 7).
musica(9, "Sulfur", ["Guitarra", "Bateria", "Baixo", "Teclado"], ["Corey Taylor", "Jim Root", "Shawn Crahan", "Sid Wilson", "Craig Jones", "Alessandro Venturella", "Jay Weinberg"], "Heavy Metal", "15/06/2009", "My guilt and my shame...", "Slipknot", 8).
musica(10, "People = Shit", ["Guitarra", "Bateria", "Baixo", "Teclado"], ["Corey Taylor", "Jim Root", "Shawn Crahan", "Sid Wilson", "Craig Jones", "Alessandro Venturella", "Jay Weinberg"], "Heavy Metal", "17/09/2001", "Come on, get down with the sickness...", "Slipknot", 9).
musica(11, "Numb", ["Vocal", "Guitarra", "Baixo", "Bateria", "Teclado"], ["Chester Bennington", "Mike Shinoda", "Brad Delson", "Rob Bourdon", "Dave 'Phoenix' Farrell", "Joe Hahn"], "Rock Alternativo", "08/05/2003", "I'm tired of being what you want me to be...", "Linkin Park", 9).
musica(12, "In the End", ["Vocal", "Guitarra", "Baixo", "Bateria", "Teclado"], ["Chester Bennington", "Mike Shinoda", "Brad Delson", "Rob Bourdon", "Dave 'Phoenix' Farrell", "Joe Hahn"], "Rock Alternativo", "20/11/2001", "It starts with one thing, I don't know why...", "Linkin Park", 9).
musica(13, "Crawling", ["Vocal", "Guitarra", "Baixo", "Bateria", "Teclado"], ["Chester Bennington", "Mike Shinoda", "Brad Delson", "Rob Bourdon", "Dave 'Phoenix' Farrell", "Joe Hahn"], "Rock Alternativo", "01/03/2001", "Crawling in my skin...", "Linkin Park", 8).
musica(14, "Somewhere I Belong", ["Vocal", "Guitarra", "Baixo", "Bateria", "Teclado"], ["Chester Bennington", "Mike Shinoda", "Brad Delson", "Rob Bourdon", "Dave 'Phoenix' Farrell", "Joe Hahn"], "Rock Alternativo", "17/02/2003", "When this began, I had nothing to say...", "Linkin Park", 8).
musica(15, "One Step Closer", ["Vocal", "Guitarra", "Baixo", "Bateria", "Teclado"], ["Chester Bennington", "Mike Shinoda", "Brad Delson", "Rob Bourdon", "Dave 'Phoenix' Farrell", "Joe Hahn"], "Rock Alternativo", "25/09/2000", "I cannot take this anymore...", "Linkin Park", 8).
musica(16, "Breaking the Habit", ["Vocal", "Guitarra", "Baixo", "Bateria", "Teclado"], ["Chester Bennington", "Mike Shinoda", "Brad Delson", "Rob Bourdon", "Dave 'Phoenix' Farrell", "Joe Hahn"], "Rock Alternativo", "14/07/2003", "Memories consume, like opening the wound...", "Linkin Park", 9).
musica(17, "Leave Out All the Rest", ["Vocal", "Guitarra", "Baixo", "Bateria", "Teclado"], ["Chester Bennington", "Mike Shinoda", "Brad Delson", "Rob Bourdon", "Dave 'Phoenix' Farrell", "Joe Hahn"], "Rock Alternativo", "18/06/2008", "I dreamed I was missing, you were so scared...", "Linkin Park", 8).
musica(18, "From the Inside", ["Vocal", "Guitarra", "Baixo", "Bateria", "Teclado"], ["Chester Bennington", "Mike Shinoda", "Brad Delson", "Rob Bourdon", "Dave 'Phoenix' Farrell", "Joe Hahn"], "Rock Alternativo", "15/11/2003", "I don't know who to trust, no surprise...", "Linkin Park", 8).
musica(19, "Papercut", ["Vocal", "Guitarra", "Baixo", "Bateria", "Teclado"], ["Chester Bennington", "Mike Shinoda", "Brad Delson", "Rob Bourdon", "Dave 'Phoenix' Farrell", "Joe Hahn"], "Rock Alternativo", "28/02/2001", "Why does it feel like night today?", "Linkin Park", 7).
musica(20, "Faint", ["Vocal", "Guitarra", "Baixo", "Bateria", "Teclado"], ["Chester Bennington", "Mike Shinoda", "Brad Delson", "Rob Bourdon", "Dave 'Phoenix' Farrell", "Joe Hahn"], "Rock Alternativo", "02/05/2003", "I am a little bit of loneliness...", "Linkin Park", 9).
musica(21, "Ma Chérie", ["Vocal", "Guitarra", "Bateria", "Piano"], ["Remington Leith", "Sebastian Danzig", "Emerson Barrett"], "Rock Alternativo", "12/03/2012", "Ma chérie, I would die for you...", "Palaye Royale", 8).
musica(22, "Mr. Doctor Man", ["Vocal", "Guitarra", "Bateria", "Piano"], ["Remington Leith", "Sebastian Danzig", "Emerson Barrett"], "Rock Alternativo", "03/09/2013", "Mr. Doctor Man, I can't be cured...", "Palaye Royale", 7).
musica(23, "Hang on to Yourself", ["Vocal", "Guitarra", "Bateria", "Piano"], ["Remington Leith", "Sebastian Danzig", "Emerson Barrett"], "Rock Alternativo", "22/07/2014", "It's a sad, sad thing...", "Palaye Royale", 8).
musica(24, "Lonely", ["Vocal", "Guitarra", "Bateria", "Piano"], ["Remington Leith", "Sebastian Danzig", "Emerson Barrett"], "Rock Alternativo", "19/06/2017", "I don't want to be alone...", "Palaye Royale", 9).
musica(25, "You'll Be Fine", ["Vocal", "Guitarra", "Bateria", "Piano"], ["Remington Leith", "Sebastian Danzig", "Emerson Barrett"], "Rock Alternativo", "24/05/2019", "I've been catching your light...", "Palaye Royale", 7).
musica(26, "Don't Feel Quite Right", ["Vocal", "Guitarra", "Bateria", "Piano"], ["Remington Leith", "Sebastian Danzig", "Emerson Barrett"], "Rock Alternativo", "18/12/2015", "The room's a mess, but it'll feel like home soon...", "Palaye Royale", 8).
musica(27, "Love the Void", ["Vocal", "Guitarra", "Bateria", "Piano"], ["Remington Leith", "Sebastian Danzig", "Emerson Barrett"], "Rock Alternativo", "05/10/2018", "Don't, don't stop the music...", "Palaye Royale", 8).
musica(28, "How Do You Do?", ["Vocal", "Guitarra", "Bateria", "Piano"], ["Remington Leith", "Sebastian Danzig", "Emerson Barrett"], "Rock Alternativo", "09/04/2013", "How do you do? How do you do?", "Palaye Royale", 7).
musica(29, "Get Higher", ["Vocal", "Guitarra", "Bateria", "Piano"], ["Remington Leith", "Sebastian Danzig", "Emerson Barrett"], "Rock Alternativo", "14/02/2016", "You've been killing the spark...", "Palaye Royale", 8).
musica(30, "Massacre, The New American Dream", ["Vocal", "Guitarra", "Bateria", "Piano"], ["Remington Leith", "Sebastian Danzig", "Emerson Barrett"], "Rock Alternativo", "10/11/2019", "The dead man walking...", "Palaye Royale", 9).
musica(31, "Get Well Soon", ["Vocal", "Guitarra", "Bateria", "Piano"], ["Remington Leith", "Sebastian Danzig", "Emerson Barrett"], "Rock Alternativo", "15/03/2015", "I don't like you, do you like me?", "Palaye Royale", 8).
musica(32, "Someone Like You", ["Vocal", "Piano"], ["Adele"], "Soul", "24/01/2011", "Never mind, I'll find someone like you...", "Adele", 9).
musica(33, "Hello", ["Vocal", "Piano"], ["Adele"], "Soul", "23/10/2015", "Hello, it's me, I was wondering if after all these years...", "Adele", 8).
musica(34, "Shape of You", ["Vocal", "Guitarra", "Teclado"], ["Ed Sheeran"], "Pop", "06/01/2017", "The club isn't the best place to find a lover...", "Ed Sheeran", 9).
musica(35, "Thinking Out Loud", ["Vocal", "Guitarra"], ["Ed Sheeran"], "Pop", "24/09/2014", "When your legs don't work like they used to before...", "Ed Sheeran", 8).
musica(36, "Halo", ["Vocal", "Piano"], ["Beyoncé"], "R&B", "20/01/2009", "Remember those walls I built? Well, baby, they're tumbling down...", "Beyoncé", 9).
musica(37, "Single Ladies (Put a Ring on It)", ["Vocal", "Bateria"], ["Beyoncé"], "R&B", "13/10/2008", "All the single ladies (All the single ladies)...", "Beyoncé", 8).
musica(38, "Sorry", ["Vocal", "Guitarra"], ["Justin Bieber"], "Pop", "23/10/2015", "You gotta go and get angry at all of my honesty...", "Justin Bieber", 8).
musica(39, "Love Yourself", ["Vocal", "Guitarra"], ["Justin Bieber"], "Pop", "09/11/2015", "For all the times that you rain on my parade...", "Justin Bieber", 7).
musica(40, "Love Story", ["Vocal", "Guitarra"], ["Taylor Swift"], "Country Pop", "12/09/2008", "We were both young when I first saw you...", "Taylor Swift", 9).
musica(41, "Shake It Off", ["Vocal", "Guitarra"], ["Taylor Swift"], "Pop", "18/08/2014", "I stay out too late, got nothin' in my brain...", "Taylor Swift", 8).
musica(42, "Hotline Bling", ["Vocal", "Teclado"], ["Drake"], "Hip-Hop", "31/07/2015", "You used to call me on my cell phone...", "Drake", 8).
musica(43, "In My Feelings", ["Vocal", "Teclado"], ["Drake"], "Hip-Hop", "10/07/2018", "Kiki, do you love me? Are you riding?", "Drake", 7).
musica(44, "Thank U, Next", ["Vocal", "Teclado"], ["Ariana Grande"], "Pop", "03/11/2018", "Thought I'd end up with Sean, but he wasn't a match...", "Ariana Grande", 9).
musica(45, "No Tears Left to Cry", ["Vocal", "Teclado"], ["Ariana Grande"], "Pop", "20/04/2018", "Right now, I'm in a state of mind...", "Ariana Grande", 8).
musica(46, "Uptown Funk", ["Vocal", "Guitarra", "Baixo", "Bateria", "Teclado"], ["Bruno Mars"], "Funk", "10/11/2014", "This hit, that ice cold, Michelle Pfeiffer, that white gold...", "Bruno Mars", 9).
musica(47, "Just the Way You Are", ["Vocal", "Piano"], ["Bruno Mars"], "Pop", "20/07/2010", "Oh, her eyes, her eyes make the stars look like they're not shining...", "Bruno Mars", 8).
musica(48, "Diamonds", ["Vocal", "Teclado"], ["Rihanna"], "Pop", "27/09/2012", "Shine bright like a diamond...", "Rihanna", 9).
musica(49, "We Found Love", ["Vocal", "Teclado"], ["Rihanna"], "Pop", "22/09/2011", "Yellow diamonds in the light...", "Rihanna", 8).
musica(50, "All of Me", ["Vocal", "Piano"], ["John Legend"], "R&B", "12/08/2013", "What would I do without your smart mouth?...", "John Legend", 9).
musica(51, "Ordinary People", ["Vocal", "Piano"], ["John Legend"], "R&B", "08/10/2004", "Girl, I'm in love with you...", "John Legend", 8).
